# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92dc87aaa67a9916e40e2f8bd065e13512aa2048fa0a17ff5fed6554dca3d12e1921b4650dbc24d3b8819ef93b8c0b57b1f81b9ce61ff3150b5a27ff9d8d29da

test:
  secret_key_base: 133ca6d5b551d57a986ca9370b37eefa8e766cc8768be201accb0aff560488b22d4f8613ec6325a47098a13c49b7c70f8fc7256c2089b5ce7ea9c552224045bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
